### ISSUE TITLE
Add UI for sentiment indicators.

### ISSUE THREAD

**Issue by ericdudley** [agblox/ui_proto#15]
From Tom:
## guidelines for the Research Interface:  Each asset has 5 indicators
- Sentiment Score: a numeric measure of the bullishness /bearishness of news coverage of the stock.
- Sentiment High / Low: highest and lowest intraday sentiment scores.
- News Volume: the absolute number of news articles covering the stock.
- News Buzz: a numeric measure of the change in coverage volume for the stock.

Perhaps we could break these down into one or more chart types. Another option would be to add this into the stats section of the charts. 
Maybe we could dedicate a new section above or below the charts/articles that displays this info.

**Comment by ericdudley** [comment]
@tbosch82 What are your thoughts on this?

**Comment by tbosch82** [comment]
@ericdudley I think it would be ideal to have all of this in one location, the problem is each dashboard isn't necessarily configured for an individual stock. Maybe it would be best to put this on the trading screen so the information is displayed depending on what stock ticker is selected?

**Comment by tbosch82** [comment]
Didn't mean to close this.

**Comment by ericdudley** [comment]
First version of this implemented based on [StockFluence](https://www.stockfluence.com/).
