### ISSUE TITLE
Add some utility CSS classes.

### ISSUE THREAD

**Issue by ericdudley** [agblox/ui_proto#21]
Many CSS classes have been needed just to add spacing around things. We should add some utility classes to `index.scss` to be able to add different multiples of `$spacing` with `className`.

Example:
`ml-1` -> `margin-left: $spacing;`
`mr-2` -> `margin-left: $spacing * 2;`
`ml-1-2` -> `margin-left: $spacing / 2;`

**Comment by tbosch82** [comment]
The following utility classes were added to index.scss:

.left-spacing {
  margin-left: $spacing;
}

.left-spacing-2 {
  margin-left: $spacing * 2;
}

.right-spacing {
  margin-right: $spacing;
}

.top-spacing {
  margin-top: $spacing;
}

.top-spacing-2 {
  margin-top: $spacing * 2;
}

.all-spacing {
  margin: $spacing;
}

.field-time {
  text-align: center;
  width: $field-width / 2;
  height: $field-height;
}

.field-select {
  width: $field-width;
}

.field-text {
  width: $field-width;
  height: $field-height;
}
