### ISSUE TITLE
Add support for time series charts.

### ISSUE THREAD

**Issue by ericdudley** [agblox/ui_proto#3]
Tasks
- [x] Add UI for choosing data sources
- [x] Render charts with selected data
- [x] Persist chart state

Blockers
- [x] Support time series data through API endpoint

Add support for time series charts. The API will provide several endpoints that expose time series data, price over time, volume time, etc.

The charts should be time series charts that support changing of data source. Probably should use a multi-select that contains all the data sources.

https://plot.ly/javascript/time-series/ use Plotly scatter plot in lines mode.

[Month Codes](https://www.cmegroup.com/month-codes.html)
[Product Codes](https://www.cmegroup.com/trading/products/)

**Comment by IaroslavR** [comment]
@akurzhan what we can provide as a first source of time-series?

**Comment by ericdudley** [comment]
First commodities time series data is supported.
