### ISSUE TITLE
Add support for text data charts.

### ISSUE THREAD

**Issue by ericdudley** [agblox/ui_proto#4]
Add charts to visualize text data. Charts should be able to convey word prevalence and popularity.

Tasks
- [x] Create UI for selecting type of chart
- [x] Create text data charts
- [x] Integrate with data from API

Blockers
- [x] Need popularity/favorites/retweets value to be exposed by API in `Tweet` schema
- [x] Need tweet id to be exposed by API in `Tweet` schema in order to be able to link to a specific tweet

**Comment by ericdudley** [comment]
@IaroslavR @akurzhan If you could check out the blockers here, I need some more data to be exposed by the API. Related issue -> #5

**Comment by IaroslavR** [comment]
> Need tweet id to be exposed by API in Tweet schema in order to be able to link to a specific tweet  

closed in https://github.com/agblox/research-lab/pull/27

**Comment by IaroslavR** [comment]
> Add charts to visualize text data. Charts should be able to convey word prevalence and popularity.
> 
> Tasks
> 
> * [x]  Create UI for selecting type of chart
> * [ ]  Create text data charts
> * [ ]  Integrate with data from API
> 
> Blockers
> 
> * [ ]  Need popularity/favorites/retweets value to be exposed by API in `Tweet` schema
> * [x]  Need tweet id to be exposed by API in `Tweet` schema in order to be able to link to a specific tweet

@ericdudley About `popularity` Which attribute of tweet you are wanted here?

**Comment by IaroslavR** [comment]
@akurzhan We collect favorites/retweets values at time of scraping and **do not update this value in the further scraper runs** but technically it's possible. Are we need it?

**Comment by ericdudley** [comment]
@IaroslavR We could add a `popularity` column that is computed based on retweets/favorites during ingest. In the mean time, we could just expose `favorites` and `retweets` as two additional columns.

**Comment by ericdudley** [comment]
Support basic charts for text data, currently only supporting tweets as a source.
