### ISSUE TITLE
front page at www.agblox.com

### ISSUE THREAD

**Issue by akurzhan** [agblox/ui_proto#8]
@IaroslavR Our front page https://agblox.com is accessed properly, but if we use URL www.agblox.com - it gives an error.
Can we fix?

**Comment by IaroslavR** [comment]
Confirmed https://www.agblox.com/ sertificate error in Firefox 67.0 (64-bit)

**Comment by IaroslavR** [comment]
@akurzhan checked in Firefox 67.0 (64-bit) and  Chrom 74.0.3729.169 (Official Build) (64-bit)
